// Generated by scripts/write-build-info.mjs during npm run build.
export const buildInfo = {
  builtAt: "2026-06-16T20:21:08.372Z",
  commitSha: "",
  shortSha: "",
  commitRef: "",
  commitDate: null,
} as const;
