// Generated by scripts/write-build-info.mjs during npm run build.
export const buildInfo = {
  builtAt: "2026-07-03T11:37:25.704Z",
  commitSha: "d311c8102161f9285a6fa4a7de6db374ca74ef3e",
  shortSha: "d311c81",
  commitRef: "codex/ui-performance-usability-sprint",
  commitDate: "2026-07-03T13:33:00+02:00",
} as const;
