name: Build and deploy Kmail website

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: arn:aws:iam::149172093612:role/GitHubKmailWorkflowRole
      #     aws-region: us-east-1

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: docker/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ steps.login-ecr.outputs.registry }}/props-app:${{ github.sha }}

  deploy:
    name: Compose docker services on a remote host
    environment: production
    runs-on: ubuntu-latest
    needs: build-docker-image
    env:
      DOMAIN: props.knote.com
      AWS_REMOTE_HOST: props.knote.com
      AWS_REMOTE_USER: ec2-user
      SSH_KEY_NAME: deploy-key.pem
      SSH_KEY_PATH: ~/.ssh/deploy-key.pem
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::149172093612:role/GitHubKmailWorkflowRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: ${{ env.SSH_KEY_NAME }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Upload artifacts to the remote
        run: |
          mv docker/docker-compose.yml docker-compose.yml
          mv conf/${{ env.DOMAIN }}.json settings.json
          scp -i ${{ env.SSH_KEY_PATH }} docker-compose.yml settings.json ${{ env.AWS_REMOTE_USER }}@${{ env.AWS_REMOTE_HOST }}:.

      - name: Run updated services
        uses: appleboy/ssh-action@v0.1.10
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REGISTRY_USER: ${{ steps.login-ecr.outputs.docker_username_296506983298_dkr_ecr_eu_central_1_amazonaws_com }}
          REGISTRY_PASS: ${{ steps.login-ecr.outputs.docker_password_296506983298_dkr_ecr_eu_central_1_amazonaws_com }}
          IMAGE: ${{ steps.login-ecr.outputs.registry }}/props-app
          # IMAGE_TAG: ${{ github.sha }}
          IMAGE_TAG: 45668722a53cc5964edcdebb6066f4afb70c884e	
          HOSTNAME: ${{ env.DOMAIN }}
          ROOT_URL: http://${{ env.DOMAIN }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAINS: ${{ secrets.MAILGUN_DOMAINS }}
        with:
          host: ${{ env.AWS_REMOTE_HOST }}
          username: ${{ env.AWS_REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: |
            REGISTRY,
            REGISTRY_USER,
            REGISTRY_PASS,
            IMAGE,
            IMAGE_TAG,
            HOSTNAME,
            ROOT_URL,
            MAILGUN_API_KEY,
            MAILGUN_DOMAINS
          script: |
            echo $REGISTRY_PASS | docker login -u $REGISTRY_USER --password-stdin $REGISTRY
            # export METEOR_SETTINGS=$(cat settings.json)
            # docker-compose down
            # docker-compose up -d
